name: 🚀 Publish

on:
  push:
    tags:
      - 'podbee-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating the GitHub release
      packages: write # Required for pushing to GitHub Container Registry
    steps:
    - name: ⬇️ Check out code
      uses: actions/checkout@v3
    - name: Version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]
        then
            tag=${GITHUB_REF##refs/tags/}
            v=${tag##podbee-}
            echo "::set-output name=version::$v"
        else
            echo "::set-output name=version::$GITHUB_SHA"
        fi
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: PodBee ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.10.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: Build and push PodBee image
      id: build-and-push
      uses: docker/build-push-action@v4.2.1
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: |
          ghcr.io/biznesbees/podbee:${{ steps.version.outputs.version }}
